name: Release

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1.2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Generate package
      run: dotnet pack -c Release --no-build -o .\

    - name: Publish the package
      run: nuget push .\*.nupkg -NonInteractive -SkipDuplicate -Source 'https://api.nuget.org/v3/index.json'

    - name: Publish the symbols
      run: nuget push .\*.snupkg -NonInteractive -SkipDuplicate -Source 'https://api.nuget.org/v3/index.json'